export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const USER_LOADED='USER_LOADED';//for successfully user loaded
export const AUTH_ERROR='AUTH_ERROR';//token not matched
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT='LOGOUT';
//export const GET_PROFILE='GET_PROFILE';
//export const PROFILE_ERROR='PROFILE_ERROR';
//export const CLEAR_PROFILE='CLEAR_PROFILE';
export const GET_CONSUMER='GET_CONSUMER';
export const CONSUMER_ERROR='CONSUMER_ERROR';
export const CLEAR_CONSUMER='CLEAR_CONSUMER';
